### ISSUE TITLE
where is training data?

### ISSUE THREAD

**Issue by shendaizi** [pannous/tensorflow-ocr#1]
@pannous ,when i train the tensorflow-ocr, I can't find the training data the system input. and when i type the ./train_ocr_layer, there are throwing an error: Exception: BAD FONT: /usr/share/texlive/texmf-dist/fonts/truetype/public/dejavu/DejaVuSansMono-Oblique.ttf.

**Comment by pannous** [comment]
this project uses fonts on your system for generating training data on the fly.
 the "bad font" exceptions are now caught.
