### ISSUE TITLE
beginning to do research on OCR using tensorflow

### ISSUE THREAD

**Issue by shaolinkhoa** [pannous/tensorflow-ocr#2]
Dear sir,

I just start learning about Neural Network and I found Tensorflow is easy to use.
 
I learn tensorflow by running example from this tutorial https://github.com/nlintz/TensorFlow-Tutorials and reading this book deeplearningbook.org.

My goal is use Neural network to recognize each letters and number (eg: a,b...x,y,z, A..Z..0...9) . So It means 62 class.

I can segment each letter from the picture by QT.

Now,I confusing about how to OCR by using tensorflow.
Cause there are a lot of project about "Handwriting recognition" but a few about "OCR for printed documents". And I a newbie so I really don't know how or where to begin.

Would you mind helping me.

1/ Can I use the same those MNIST classifiers (http://yann.lecun.com/exdb/mnist/) for recognizing English alphabet/letters ? Cause MNIST classifiers recognize digit (0 - 9) so I really don't know It could handle 62 class or not ?﻿

2/ Do you have any documents or papers about "OCR for printed documents". I really lack of knowledge.
 
3/ I found your project tensorflow-OCR . Would you mind if I learn from your code.

4/ I got errors when i run : **./train_ocr_layer.py**
```
(tensorflow)khoa@khoa:~/tensorflow/tensorflow-ocr$ ./train_ocr_layer.py 
ls: cannot access /tmp/tensorboard_logs/: No such file or directory
Traceback (most recent call last):
  File "./train_ocr_layer.py", line 4, in <module>
    import layer
  File "/home/khoa/tensorflow/tensorflow-ocr/layer/__init__.py", line 1, in <module>
    from net import *
  File "/home/khoa/tensorflow/tensorflow-ocr/layer/net.py", line 8, in <module>
    set_tensorboard_run(auto_increment=True)
  File "/home/khoa/tensorflow/tensorflow-ocr/layer/tensorboard_util.py", line 18, in set_tensorboard_run
    run_nr = get_last_tensorboard_run_nr()
  File "/home/khoa/tensorflow/tensorflow-ocr/layer/tensorboard_util.py", line 8, in get_last_tensorboard_run_nr
    logs=subprocess.check_output(["ls", tensorboard_logs]).split("\n")
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['ls', '/tmp/tensorboard_logs/']' returned non-zero exit status 2
```

Thank you and regards,
Khoa

**Comment by JPaulMora** [comment]
Run `mkdir -p /tmp/tensorboard_logs` and try again

**Comment by shaolinkhoa** [comment]
thank you. Do you know any architecture or model for OCR.
