### ISSUE TITLE
ImportError: No module named layer

### ISSUE THREAD

**Issue by vitamin** [pannous/tensorflow-ocr#7]
lack layer.py

-----
localhost:tensorflow-ocr didi$ ./train_ocr_layer.py
Traceback (most recent call last):
  File "./train_ocr_layer.py", line 3, in <module>
    import layer
ImportError: No module named layer
localhost:tensorflow-ocr didi$ pip install layer
Collecting layer
  Could not find a version that satisfies the requirement layer (from versions: )
No matching distribution found for layer

**Comment by pannous** [comment]
do
`git clone --recursive https://github.com/pannous/tensorflow-speech-recognition`
or
`pip install layer`
